//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadRogue {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Names {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Names() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SadRogue.Names", typeof(Names).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aind,Ainn,Airk,Aitze,Ald,Ance,Anxe,Ard,Ashf,Aulg,Aun,Aure,Authe,Baelt,Bakh,Bal,Balt,Balthe,Barg,Barll,Bauce,Baysc,Beek,Beele,Berl,Bersch,Beyn,Bhozt,Birme,Birr,Bjanc,Blaen,Blize,Blouch,Blurk,Blynze,Bokk,Borl,Borse,Brahl,Brakk,Bralk,Brang,Brann,Branth,Brem,Bress,Breun,Briint,Brill,Brize,Brod,Broik,Brolt,Bront,Broozh,Brosck,Broud,Brud,Brule,Brun,Bulse,Bunth,Byar,Byst,Caer,Cail,Canth,Carn,Cayrl,Ceyt,Chaeng,Chail,Chaith,Chal,Chalm,Charg,Charn,Chave,Chayle,Chaze,Cheal,Cheev,Chel,Chern,Cherze,Chezl,Chilk,Chlenk,Ch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string multiple_syllable {
            get {
                return ResourceManager.GetString("multiple_syllable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aind,Ainn,Airk,Aitze,Ald,Ance,Anxe,Ard,Ashf,Aulg,Aun,Aure,Authe,Baelt,Bakh,Bal,Balt,Balthe,Barg,Barll,Bauce,Baysc,Beek,Beele,Berl,Bersch,Beyn,Bhozt,Birme,Birr,Bjanc,Blaen,Blize,Blouch,Blurk,Blynze,Bokk,Borl,Borse,Brahl,Brakk,Bralk,Brang,Brann,Branth,Brem,Bress,Breun,Briint,Brill,Brize,Brod,Broik,Brolt,Bront,Broozh,Brosck,Broud,Brud,Brule,Brun,Bulse,Bunth,Byar,Byst,Caer,Cail,Canth,Carn,Cayrl,Ceyt,Chaeng,Chail,Chaith,Chal,Chalm,Charg,Charn,Chave,Chayle,Chaze,Cheal,Cheev,Chel,Chern,Cherze,Chezl,Chilk,Chlenk,Ch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string one_syllable {
            get {
                return ResourceManager.GetString("one_syllable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abadapnyr,Abrethendar,Acrasian,Adario,Adieseth,Adilikor,Adinalar,Adriaxa,Afelanidd,Aforvalon,Agiora,Agreliwin,
        ///Aguidran,Aguilla,Aikikia,Akitarka,Alanahetra,Alarion,Alartia,Alarurigu,Alcidio,Aldarian,Alelakon,Aleshmara,Aletorim,
        ///Aleuworust,Alianala,Alicindra,Allessanya,Alorassanz,Amafeyan,Amathenar,Amdaramast,Amiria,Amriffien,Anaumiantis,
        ///Anelofar,Angetenar,Angurvidel,Animeldio,Anixido,Ankitarla,Ansamanthion,Ansimantar,Anspiladri,Antillia,Aphiana,
        ///Aptolcater,Aptrinuptium,Aquilia,Aradlumé,Araledek,Aramanz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string three_syllable {
            get {
                return ResourceManager.GetString("three_syllable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aahdret,Aarlen,Aasren,Aastrasl,Aban,Abbith,Ablif,Aboas,Abrance,Abrax,Abryn,Abyok,Acear,Acfyst,Achekk,Achelse,Achlarg,Achren,Achriss,Ackvold,Acram,Acu,Adaon,Addanc,Adeil,Adire,Adlay,Adlen,Adlon,Admel,Adoin,Adon,Adrek,Adreln,Adrich,Adrilc,Adurthe,Aduush,Aealim,Aeddan,Aedha,Aedir,Aedlynx,Aeiran,Aelis,Aelma,Aemon,Aenet,Aenthu,Aeprox,Aeren,Aerind,Aerkoon,Aerkour,Aerlithe,Aeron,Aeryle,Aethlyr,Aethon,Afenk,Affraig,Afraaj,Agburz,Ageen,Aghil,Aghill,Aglin,Agroth,Agwyn,Agyorl,Ahmré,Aia,Aiaia,Aibmab,Aidajn,Aiden,Aidon, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string two_syllable {
            get {
                return ResourceManager.GetString("two_syllable", resourceCulture);
            }
        }
    }
}
